config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  get 'about', to: 'welcome#about'

  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  resources 'films'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all.where(archived: false).order("order_sort DESC")
    @archived_films = Film.all.where(archived: true).order("name ASC")
  end

  def new
    if admin?
      @film = Film.new
    else
      redirect_to root_url
    end
  end

  def create
    @film = Film.new(film_params)

      if @film.save
        redirect_to(
          films_path,
          notice: "Film created successfully!"
        )
      else
        render :new, notice: "Error creating film"
      end
  end

  def show
    @film = Film.friendly.find(params[:id])
  end

  def edit
    if admin?
      @film = Film.friendly.find(params[:id])
    else
      redirect_to root_url
    end
  end

  def update
    @film = Film.friendly.find(params[:id])

    if @film.update(film_params)
        redirect_to(
          film_path(@film),
          notice: "Film Updated Successfully"
        )
      else
        render "edit", status: 400
      end
  end

  def destroy
    film = Film.friendly.find(params[:id])
      film.destroy!

      redirect_to(
        films_path,
        notice: "Film Deleted"
      )
  end

  private

  def film_params
    params.require(:film).permit(
        :name,
        :synopsis,
        :trailer_url,
        :poster_url,
        :press_url,
        :release_date,
        :theater_dates,
        :past_dates,
        :featured,
        :archived,
        :film_page,
        :offsite_link,
        :order_sort
      )
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_url, notice: "Message received, thanks!"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @featured_films = Film.where(featured: true).sample(3)
  end

  def about
    @featured_films = Film.where(featured: true).sample(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def admin?
    if logged_in?
      current_user.admin?
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/films/edit.slim
.row
  .col-xs-12.col-sm-10.col-sm-offset-1
    .content-tile.p-a-1
      h1.m-b-1.header Edit #{@film.name}
      .film-form.p-a-1
        = form_for @film do |f|
          .row
            .col-xs-12
              = f.label "Film Name"
              = f.text_field :name

              = f.label "Film Synopsis"
              = f.text_area :synopsis, placeholder: "Surround italicized text with <i></i>."

              = f.label "YouTube Trailer Url"
              = f.text_field :trailer_url, placeholder: "ex: http://www.youtube.com/9212019"

              .tip This is located in YouTube's embed code. Click "share" on a YouTube video, then embed, and then find the url within the embed code. For example:
              .tip.m-b-2 &lt;iframe width="560" height="315" src="<b>https://www.youtube.com/embed/sAryMieZcuo</b>" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen&gt;&lt;/iframe&gt;

              = f.label "Poster Url"
              = f.text_field :poster_url, placeholder: "ex: http://www.imagehost.com/img/9212019"

              = f.label "Press Url"
              = f.text_field :press_url, placeholder: "ex: http://www.dropbox.com/9212019"

              = f.label "Sort Order"
              = f.number_field :order_sort

              .tip.m-b-2 Higher numbers appear higher on the index page.

              = f.label "Release Date"
              = f.text_field :release_date

              = f.label "Theater Dates"
              = f.text_area :theater_dates

              = f.label "Past Dates"
              = f.text_area :past_dates

          .row
            .col-xs-12
              = f.check_box :featured, class: "checkbox-inline"
              = f.label "Feature this film on the homepage and elsewhere?"

          .row
            .col-xs-12
              = f.check_box :archived, class: "checkbox-inline"
              = f.label "Archive this film?"

          .row
            .col-xs-12
              = f.check_box :film_page, class: "checkbox-inline"
              = f.label "Should this film have a page on Cartilage Films?"

          .row
            .col-xs-12
              = f.label "Off site link (previous checkbox must be unchecked)"
              = f.text_field :offsite_link, placeholder: "ex: http://www.screenmedia.com/films/9212019"

          .row
            .col-xs-12
              = f.submit 'Update Film', class: "button submit-button button--yes"

app/views/films/index.slim
.row
  .col-xs-12.col-sm-10.col-sm-offset-1
    .content-tile

      - if admin?
        = link_to "Add New Film", new_film_path, class: "button button--yes float-right"

      h2.header.text-left IN THEATERS & COMING SOON
      .row
        - @films.each do |film|
          .col-xs-12.col-sm-6.col-md-4
            .film-block
              - if admin? && film.featured == true
                .admin-featured-tag Featured

              - if film.film_page == true || admin?
                = link_to film do
                  .film-poster-block
                    - if film.poster_url.blank?
                      = image_tag("artsoon.jpg")
                    - else
                      = image_tag(film.poster_url)
                .film-title-block
                  = link_to film do
                    h3.header = film.name

              - elsif !film.offsite_link.blank?
                = link_to film.offsite_link, target: "_blank" do
                  .film-poster-block
                    - if film.poster_url.blank?
                      = image_tag("artsoon.jpg")
                    - else
                      = image_tag(film.poster_url)
                .film-title-block
                  = link_to film.offsite_link, target: "_blank" do
                    h3.header = film.name

              - else
                .film-poster-block
                  - if film.poster_url.blank?
                    = image_tag("artsoon.jpg")
                  - else
                    = image_tag(film.poster_url)
                .film-title-block
                  h3.header = film.name


      h2.header.text-left PAST RELEASES
      .row
        - @archived_films.each do |film|
          .col-xs-12.col-sm-6.col-md-4
            .film-block
              - if admin? && film.featured == true
                .admin-featured-tag Featured

              - if film.film_page == true || admin?
                = link_to film do
                  .film-poster-block
                    - if film.poster_url.blank?
                      = image_tag("artsoon.jpg")
                    - else
                      = image_tag(film.poster_url)
                .film-title-block
                  = link_to film do
                    h3.header = film.name

              - elsif !film.offsite_link.blank?
                = link_to film.offsite_link, target: "_blank" do
                  .film-poster-block
                    - if film.poster_url.blank?
                      = image_tag("artsoon.jpg")
                    - else
                      = image_tag(film.poster_url)
                .film-title-block
                  = link_to film.offsite_link, target: "_blank" do
                    h3.header = film.name

              - else
                .film-poster-block
                  - if film.poster_url.blank?
                    = image_tag("artsoon.jpg")
                  - else
                    = image_tag(film.poster_url)
                .film-title-block
                  h3.header = film.name

app/views/films/new.slim
.row
  .col-xs-12.col-sm-10.col-sm-offset-1
    .content-tile.p-a-1
      h1.m-b-1.header Add a Film
      .film-form.p-a-1
        = form_for @film do |f|
          .row
            .col-xs-12
              = f.label "Film Name"
              = f.text_field :name

              = f.label "Film Synopsis"
              = f.text_area :synopsis, placeholder: "Surround italicized text with <i></i>."

              = f.label "Youtube Trailer Url"
              = f.text_field :trailer_url, placeholder: "ex: https://www.youtube.com/embed/sAryMieZcuo"

              .tip This is located in YouTube's embed code. Click "share" on a YouTube video, then embed, and then find the url within the embed code. For example:
              .tip.m-b-2 &lt; iframe width="560" height="315" src="https://www.youtube.com/embed/sAryMieZcuo" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen&gt;&lt;/iframe&gt;

              = f.label "Poster Url"
              = f.text_field :poster_url, placeholder: "ex: http://www.imagehost.com/img/9212019"

              = f.label "Press Url"
              = f.text_field :press_url, placeholder: "ex: http://www.dropbox.com/9212019"

              = f.label "Sort Order"
              = f.number_field :order_sort

              .tip.m-b-2 Higher numbers appear higher on the index page.

              = f.label "Release Date"
              = f.text_field :release_date

              = f.label "Theater Dates"
              = f.text_area :theater_dates

              = f.label "Past Dates"
              = f.text_area :past_dates

          .row
            .col-xs-12
              = f.check_box :featured, class: "checkbox-inline"
              = f.label "Feature this film on the homepage and elsewhere?"

          .row
            .col-xs-12
              = f.check_box :archived, class: "checkbox-inline"
              = f.label "Archive this film?"

          .row
            .col-xs-12
              = f.check_box :film_page, class: "checkbox-inline"
              = f.label "Should this film have a page on Cartilage Films?"

          .row
            .col-xs-12
              = f.label "Off site link (previous checkbox must be unchecked)"
              = f.text_field :offsite_link, placeholder: "ex: http://www.screenmedia.com/films/9212019"

          .row
            .col-xs-12
              = f.submit 'Add Film', class: "button submit-button button--yes"

app/views/films/show.slim
row
  .col-xs-12.col-sm-10.col-sm-offset-1
    .content-tile
      - if admin? && !@film.film_page

        - if !@film.offsite_link.blank?
          h3.header.sentence-case This is a preview of this film's film page. You are seeing this page because you are an admin who may need to edit or delete this film. Currently, clicking this page's poster or title on the FILMS page opens <a href="#{@film.offsite_link}" target="_blank">#{@film.offsite_link}</a> in a new tab.

        - else

          h3.header.sentence-case This is a preview of this film's film page. You are seeing this page because you are an admin who may need to edit or delete this film. Currently, this page's poster and title on the FILMS page aren't clickable.

      - if admin?
        .row
          .col-xs-12.m-b-1
            = link_to "Edit Film", edit_film_path(@film), class: "button button--maybe float-right"

        .row
          .col-xs-12.m-b-1
            = button_to "Delete Film", @film, method: :delete,
            class: "button submit-button button--no float-right",
            data: { confirm: "Are you sure you want to delete #{@film.name}?" }

      .row
        .col-xs-12.col-sm-6.col-md-5
          - if @film.poster_url.blank?
            = image_tag("artsoon.jpg", class: "full-width")
          - else
            = image_tag(@film.poster_url, class: "full-width")

          - unless @film.release_date.blank?
            h3.header = @film.release_date

          - unless @film.theater_dates.blank?
            h3.header Theaters
            = simple_format(@film.theater_dates)

          - unless @film.past_dates.blank?
            h3.header Past Cities and Theaters
            = simple_format(@film.past_dates)

        .col-xs-12.col-sm-6.col-md-7
          - unless @film.trailer_url.blank?
            .video-container
              <iframe width="100%" height="100%" src="#{@film.trailer_url}" frameborder="0" allowfullscreen></iframe>

          - unless @film.synopsis.blank?
            = simple_format(@film.synopsis)

          - unless @film.press_url.blank?
            h3.header = link_to "Press Link", @film.press_url, target: "_blank"

app/views/layouts/application.slim
<!DOCTYPE html>
html
  - controller_class = params[:controller]
  - action_class = params[:action]
  - body_class = controller_class + " " + action_class
  head
    title Cartilage Films
    = csrf_meta_tags
    <meta name="viewport" content="initial-scale=1">
    //<meta property="og:image" content="images/ian-lockwood.jpg">

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body class=body_class
    header
      nav
        .container-fluid
          .navbar-header
            button.navbar-toggle data-target="#myNavbar" data-toggle="collapse" type="button"
              span.icon-bar
              span.icon-bar
              span.icon-bar
          #myNavbar.collapse.navbar-collapse
            .navbar-left
              = link_to root_path, class: "no-hover-style" do
                = image_tag("cartilage-c.png", class: "navbar-c")
            .navbar-right
              ul.nav.navbar-nav
                li class="#{'active' if current_page?(root_path)}" = link_to "home", root_path
                li class="#{'active' if current_page?(films_path)}" = link_to "films", films_path
                li class="#{'active' if current_page?(about_path)}" = link_to "about", about_path
                li class="#{'active' if current_page?(new_message_path)}" = link_to "contact us", new_message_path
                li = link_to "Twitter", "https://twitter.com/CartilageFilms", target: "_blank"
                li = link_to "Facebook", "https://www.facebook.com/CartilageFilms/", target: "_blank"

                - if admin?
                  li = link_to "Log Out", logout_path

    .main
      = yield

    footer

app/views/messages/new.slim
.row
  .col-xs-12.col-sm-10.col-sm-offset-1
    .content-tile.p-a-1
      h1.m-b-1.header Contact Us
      .contact-form.p-a-1
        = form_for @message, url: create_message_url do |f|
          //= notice
          = @message.errors.full_messages.join(', ')

          .row
            .col-xs-12.col-sm-6
              = f.text_field :name, placeholder: 'Your Name'

            .col-xs-12.col-sm-6
              = f.email_field :email, placeholder: 'Your Email'

            .col-xs-12
              = f.text_area :body, placeholder: 'Your Message'

            .col-xs-12
              = f.submit 'Send', class: "button send-button"

app/views/welcome/about.slim
.row
  .col-xs-12.col-sm-10.col-sm-offset-1
    .content-tile.p-a-2
      h1.header About Cartilage
      h4.p-a-2 Cartilage Films was founded in 2016 as a solution for filmmakers and rightsholders to bring quality independent films to audiences in the theatrical space.

    .content-tile
      .row
        - @featured_films.each do |film|
          .col-xs-12.col-sm-6.col-md-4
            .film-block
              - if film.film_page == true || admin?
                = link_to film do
                  .film-poster-block
                    - if film.poster_url.blank?
                      = image_tag("artsoon.jpg")
                    - else
                      = image_tag(film.poster_url)
                .film-title-block
                  = link_to film do
                    h3.header = film.name

              - elsif !film.offsite_link.blank?
                = link_to film.offsite_link, target: "_blank" do
                  .film-poster-block
                    - if film.poster_url.blank?
                      = image_tag("artsoon.jpg")
                    - else
                      = image_tag(film.poster_url)
                .film-title-block
                  = link_to film.offsite_link, target: "_blank" do
                    h3.header = film.name

              - else
                .film-poster-block
                  - if film.poster_url.blank?
                    = image_tag("artsoon.jpg")
                  - else
                    = image_tag(film.poster_url)
                .film-title-block
                  h3.header = film.name

      .row
        .col-xs-12
          h3.header.float-right = link_to raw("More Films &#9654;"), films_path

app/views/welcome/index.slim
.row
  .col-xs-12.col-sm-10.col-sm-offset-1
    .content-tile
      = image_tag("logo.png", class: "max-width-1000 p-a-3")

    .content-tile
      .row
        - @featured_films.each do |film|
          .col-xs-12.col-sm-6.col-md-4
            .film-block
              - if film.film_page == true || admin?
                = link_to film do
                  .film-poster-block
                    - if film.poster_url.blank?
                      = image_tag("artsoon.jpg")
                    - else
                      = image_tag(film.poster_url)
                .film-title-block
                  = link_to film do
                    h3.header = film.name

              - elsif !film.offsite_link.blank?
                = link_to film.offsite_link, target: "_blank" do
                  .film-poster-block
                    - if film.poster_url.blank?
                      = image_tag("artsoon.jpg")
                    - else
                      = image_tag(film.poster_url)
                .film-title-block
                  = link_to film.offsite_link, target: "_blank" do
                    h3.header = film.name

              - else
                .film-poster-block
                  - if film.poster_url.blank?
                    = image_tag("artsoon.jpg")
                  - else
                    = image_tag(film.poster_url)
                .film-title-block
                  h3.header = film.name

      .row
        .col-xs-12
          h3.header.float-right = link_to raw("More Films &#9654;"), films_path

app/views/welcome/video.slim
.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/cXkMo92FZs8" frameborder="0" allowfullscreen

.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/DfaVPrNKANw" frameborder="0" allowfullscreen

.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/yyGXj3mi0AM?ecver=2" frameborder="0" allowfullscreen

.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/zXN9mCzqTAM?ecver=2" frameborder="0" allowfullscreen

.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/71SMjmnHXyA" frameborder="0" allowfullscreen

.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/3YDnWbvrsic" frameborder="0" allowfullscreen

.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/b4z7kyo8oRE" frameborder="0" allowfullscreen

.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/nqG32fuMxJE?ecver=2" frameborder="0" allowfullscreen

.content-tile
  div style="position:relative;height:0;padding-bottom:56.25%"
    iframe.youtube src="https://www.youtube.com/embed/1-cmTBCmGD8?ecver=2" frameborder="0" allowfullscreen